### PR TITLE
Use AS::Logger instead of Logger if available

### LINKED ISSUE #23: Conflict with Rails 4.2.6 and Mongoid 5.1.1
Hi,

I'm using this gem via `rails_12factor` and there is an issue with the latest Rails 4.2.6 and mongoid (5.1.1, but maybe older)

Here it is a reduced test case
https://github.com/tagliala/mongoid-rails-426/tree/rails_stdout_logging
```
~/dev/tests/mongoid-rails-426 on rails_stdout_logging $ rake routes
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/logger_silence.rb:23:in `level'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/config.rb:250:in `set_log_levels'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/config.rb:132:in `load_configuration'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/config.rb:88:in `load!'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid.rb:99:in `load!'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/railtie.rb:59:in `block in <class:Railtie>'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
~/dev/tests/mongoid-rails-426/config/environment.rb:5:in `<top (required)>'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => routes => environment
(See full trace by running task with --trace)
```

Rails 4.2.5 was fine
https://github.com/tagliala/mongoid-rails-425/tree/rails_stdout_logging

```bash
~/dev/tests/mongoid-rails-425 on rails_stdout_logging $ rake routes
You don't have any routes defined!

Please add some routes in config/routes.rb.

For more information about routes, see the Rails guide: http://guides.rubyonrails.org/routing.html.
```

Rails 4.2.6 with postgresql is also fine

This issue makes applications impossible to deploy on Heroku because `rake assets:precompile` will fail

Example: https://github.com/diowa/ruby2-rails4-bootstrap-heroku/tree/mongoid

Please try the "Deploy to Heroku" button. You could also try the `master` branch, which does not use mongoid

### PR DESCRIPTION
**Pull request by tagliala**
Use AS::Logger instead of Logger if available

ActiveSupport::LoggerThreadSafeLevel does not work with stdlib ::Logger
without monkeypatching. rails/rails#24263 introduced thread safety but
requires the target class to implement code to call an after_initialize
method if it exists. ActiveSupport::Logger has those modules included
and the correct interface implemented.

Fix #23

Refs: rails/rails#24263 heroku/rails_stdout_logging#22

### CODE REVIEW

**Comment by tagliala** [comment]
It doesn't with Rails 3.x

File: lib/rails_stdout_logging/rails.rb [hunk 1]
```diff
@@ -1,5 +1,5 @@
 module RailsStdoutLogging
-  class StdoutLogger < ::Logger
+  class StdoutLogger < ::ActiveSupport::Logger
```
Comment (carlosantoniodasilva) [inline lib/rails_stdout_logging/rails.rb]: The logger silence module is not defined there either, so I think it'd be OK to feature detect it (like it's done with the tagged logging below):

```ruby
class StdoutLogger < defined?(::ActiveSupport::Logger) ? ::ActiveSupport::Logger : ::Logger
```

@schneems any thoughts about that?

Comment (tagliala) [inline lib/rails_stdout_logging/rails.rb]: This one should work, waiting for feedback before forcing a new commit

Comment (schneems) [inline lib/rails_stdout_logging/rails.rb]: I think that should be fine, let's go ahead with that change.

I don't know how 3.x implements logger silencing. Do you know @carlosantoniodasilva ?

Comment (carlosantoniodasilva) [inline lib/rails_stdout_logging/rails.rb]: @schneems 3.x [reopens the stdlib Logger class](https://github.com/rails/rails/blob/3-2-stable/activesupport/lib/active_support/core_ext/logger.rb#L33-L41) to add silencing.

It was deprecated before 4.x, and brought back as a separate module included in AS Logger.

**Comment by schneems** [comment]
Thanks! :heart: :rocket: i'll cut a new release soon.

**Comment by tagliala** [comment]
Thank you all!

I'm opening a new issue/question

**Comment by schneems** [comment]
Tests are failing due to bundle install not working in some cases https://travis-ci.org/heroku/rails_stdout_logging/jobs/118000871

Restarting the tests on travis they continue to fail. I can't reproduce locally. I re-ran the failing tests locally and they all pass. I cut v0.0.5 with this change.

**Comment by tagliala** [comment]
> Gem::InstallError: mime-types-data requires Ruby version >= 2.0.

I don't know why that build is trying to install `mime-types-data`

https://api.travis-ci.org/jobs/118007848/log.txt?deansi=true
https://s3.amazonaws.com/archive.travis-ci.org/jobs/117950369/log.txt

**Comment by schneems** [comment]
The Rails app must have accidentally gotten it as a dependency, looks like another regression in Rails?

**Comment by tagliala** [comment]
The just released mail 2.6.4 relaxed `< 3` dependency on `mime-types-data`

https://rubygems.org/gems/mail/versions/2.6.4

**Comment by schneems** [comment]
I guess we could add mail into the appraisal gemfile. Weird that bundler doesn't see what version we're using and pick a version of the gem that is valid with our Ruby version.

Someone changed something that caused our builds to break, I feel like there is a bug to be reported somewhere but i'm not quite sure where yet. I don't think it's Mail, and I don't think it's mime-types. Bundler is my best guess.
